### ISSUE TITLE
Module 5a - Combined search

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-Training/B2FIND-Training#1]
I tried a combined search but for me the syntax is not entirely clear.

When I tried to search in B2FIND for discipline Biology in the year 2000:
```
http://b2find.eudat.eu/api/3/action/package_search?q=&ext_timeline_start=59934719570&ext_timeline_end=63314340297&discipline=Biology
```

I received an internal server error.

**Comment by hwidmann** [comment]
New 'combined search' should work now. Issue closed.
