### ISSUE TITLE
04.b-upload-metadata.md - metadata upload to CKAN

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-Training/B2FIND-Training#10]
Data upload to CKAN with mdmanager does not work:

```sh
~/B2FIND-Training$ ./mdmanager.py --mode u -c fishproject -s http://localhost:8181/oai/provider --mdsubset sample_1 --mdprefix oai_dc -i 145.100.59.214 auth=<token>

Version:  	2.0
Run mode:   	Uploading
Start : 	2016-12-07 13:03:29

ERROR in  mdmanager	process_upload	2241 : [ERROR] The directory "/home/b2find/B2FIND-Training/oaidata/fishproject-oaidata/oai_dc/sample_1" does not exist! No files for uploading are found!
(Maybe your upload list has old items?)
```

The path in the script is wrong. The real path is:
```sh
b2find@ubuntu:~/B2FIND-Training$ ls /home/b2find/B2FIND-Training/oaidata/fishproject-oai_dc/sample_1/
```

**Comment by hwidmann** [comment]
The issue with tteh wrong path is fixed, but upload causes still some problems :-(

**Comment by hwidmann** [comment]
Fixed some other isssues with commit 9c6bb49210badba8142ccf403516f661797d4236 , for me uploading to the training instance works now :  
$ ./mdmanager.py --mode u -c fishproject -s http://localhost:8181/oai/provider --mdsubset sample_1 --mdprefix oai_dc -i trng-b2find.eudat.eu
Please try it again with your CKAN instance. If it is still not working, we can do two things : 
1. Please check the web log on your CKAN server, e.g. on trng-eudat.dkrz.de is it : 
 sudo tail /etc/httpd/logs/ckan_default.error.log 
2. Let me know if you want to try it with the Training instance and I give you teh API-key for it

**Comment by chStaiger** [comment]
Still no success uploading the json documents.
1. Datacite ANDS (group 'datacite' )
 ```sh
[admincentos@b2find B2FIND-Training]$ ./mdmanager.py --mode u -c datacite -s http://localhost:8181/oai/provider --mdsubset ANDS.CENTRE-1 --mdprefix oai_dc -i 145.100.59.86:8080 --auth ****
|- Run mode:   	Uploading
|- Start : 	2018-07-19 13:50:37

|- Community datacite
 |- MD prefix oai_dc
 |- Subset ANDS.CENTRE-1 
```
No files uploaded

2. Fishproject
 ```sh
 [admincentos@b2find B2FIND-Training]$./mdmanager.py --mode u -c fishproject -s http://localhost:8181/oai/provider --mdsubset sample_1 --mdprefix oai_dc -i 145.100.59.86:8080 --auth ***
|- Run mode:   	Uploading
|- Start : 	2018-07-19 13:48:59

|- Community fishproject
 |- MD prefix oai_dc
 |- Subset sample_1

CRITICAL :  [CRITICAL] Program is aborted because of a critical error! Description:
CRITICAL :  Traceback (most recent call last):
  File "./mdmanager.py", line 2023, in main
    process(options,pstat)
  File "./mdmanager.py", line 2110, in process
    process_upload(UP,reqlist,options)
  File "./mdmanager.py", line 2382, in process_upload
    jsondata=UP.check(jsondata)
  File "./mdmanager.py", line 1847, in check
    raise Exception("The mandatory field '%s' is missing" % field)
Exception: The mandatory field 'title' is missing
```

**Comment by hwidmann** [comment]
Please try again - all :-) should be fixed now

**Comment by chStaiger** [comment]
Works, but data is not nicely represented.
![screen shot 2018-07-24 at 09 43 12](https://user-images.githubusercontent.com/8696302/43124208-bb676a96-8f26-11e8-9936-a9d48925b0d6.png)

**Comment by chStaiger** [comment]
Same issue as:
https://github.com/EUDAT-Training/B2FIND-Training/issues/11
