### ISSUE TITLE
04.b-upload-metadata.md - path fixed, still errors

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-Training/B2FIND-Training#11]
If path is fixed  (see issue #10) the following error occurs:

```sh
~/B2FIND-Training$ ./mdmanager.py --mode u -c fishproject -s http://localhost:8181/oai/provider --mdsubset sample_1 --mdprefix oai_dc -i 145.100.59.214 --auth=<key> -v

Version:  	2.0
Run mode:   	Uploading
Start : 	2016-12-07 13:20:05

CRITICAL in  mdmanager	main	1939 : [CRITICAL] Program is aborted because of a critical error! Description:
CRITICAL in  mdmanager	main	1940 : Traceback (most recent call last):
  File "./mdmanager.py", line 1936, in main
    process(options,pstat)
  File "./mdmanager.py", line 2044, in process
    ]],options)
  File "./mdmanager.py", line 2295, in process_upload
    oai_id = jsondata['oai_identifier'][0]
KeyError: 'oai_identifier'

```

**Comment by hwidmann** [comment]
As well this is fixed with commit 96ae96db2a7692df5a5e4af6707816782c7b4aa7, but upload is still not working fine :-(

**Comment by hwidmann** [comment]
Should be fixed now (as well with new SurfSARA instance) :+1: 

$ ./mdmanager.py --mode u -c fishproject -s http://localhost:8181/oai/provider --mdsubset sample_1 --mdprefix oai_dc -i 145.100.59.86:8080 --auth b7e271ed-498f-4ce8-8788-e9a2fa570497
|- Run mode:   	Uploading
|- Start : 	2018-07-23 14:40:46

   |# 1    : fishproject	['ListRecords', 'oai_dc', 'sample_1'] 
	|- Started    |@ 14:40:46   |
	 |- Subdirectory sample_1 is processed
	 [==========          ]     4 ( 50%) in 1 sec
	 [====================]     8 (100%) in 2 sec
   
	|- Finished   |@ 14:40:49   |
	| Provided | Uploaded | No action | Failed |
	|        8 |      8 |         0 |      0 |

Note : The correct ckan_organization must be specified (via option or in setting.py)

Let me know, if it works know as well for you.
I close the ticket - please reopen it if still problems occur

**Comment by chStaiger** [comment]
Upload works now, but the datasets are not presented nicely:

![screen shot 2018-07-24 at 09 43 12](https://user-images.githubusercontent.com/8696302/43124060-4ef743d6-8f26-11e8-92e0-fc40794a2c0a.png)

**Comment by hwidmann** [comment]
Fine that upload now words. The ugly presentation is another issue (so, I'm closing thsi one) and it's due to usage of a blank CKAN installation without a metadata schema behind it (only default CKAN fields are supported here). But at least  title should be shown properly - likely thsi si a problem in teh mapping. Dids you check your generated JSON and the validation output ( --mode v ) ?
