### ISSUE TITLE
Questions & ambiguities in 01.b-generate-metadata.md

### ISSUE THREAD

**Issue by sararkd** [EUDAT-Training/B2FIND-Training#14]
- In Excercise 2.1, the note about semantic mapping is quite relevant, but I'm not sure what the implication is in this context. Are we suggesting that using existing DC terms in this way is incorrect or insufficient, and that an extended schema should be used? If so, how?

- seisnet-oai_dc.csv and samples/RAW_data/locations.tsv only exist in the develop branch, should they be in the master branch as well?

- I can't get Excercise 2.3 to work. The mdmanager.py file in the develop branch has some revisioning issues, so it doesn't work. Copying the mdmanager in the master branch to the develop branch I get:

./mdmanager.py --mode g -c seisnet -s samples/RAW_data/locations.tsv --mdprefix oai_dc --mdsubset locations --verb tab
|- Run mode:   	Generation
|- Start : 	2017-11-10 12:12:25

 |- Original fields:
	['Project', 'Creators', 'Publisher', 'Subject', 'Created', 'Location-Coord', 'Location-Name']
 |- Use existing mapfile	mapfiles/seisnet-oai_dc.csv
 |- Generate XML files in oaidata/seisnet-oai_dc/locations_1/xml
  |--> TienshanPamirGeodynamicsProject(TIPAGE).xml
  |--> LakeTobaseismicnetwork,Sumatra,Indonesia.xml
  |--> GEOFONSeismicNetwork.xml
  |--> TIPTIMON(TienShan-PamirMonitoringProgram)TAJIKISTAN(2012/2014).xml
Error [Errno 2] No such file or directory: 'oaidata/seisnet-oai_dc/locations_1/xml/TIPTIMON(TienShan-PamirMonitoringProgram)TAJIKISTAN(2012/2014).xml'

Maybe I have missed something because I just have three files in the oaidata/seisnet-oai_dc/locations_1/xml folder, that I think I just generated, but in any case the instructions need to be revised.

**Comment by hwidmann** [comment]
- Ad excercise 2.1. : Yes, that's still open or actual the general issue in the world of standards : It's really difficult to find an appropraite scheme that meets your specific (disciplinary) needs. So I can't as well find an existing md schema that describes properties as 'Diet' and 'Temperament` of fish. But I added the hint to look at the metadata standards at DCC.  Finally you/we have to ask an expert from fishery or zoology ....
- I added the sample and the mapfile for seisnet to the master
- Ad Excercise 2.3 : Should be fixed - please try again (in the develop branch)
- removed the 'sh' from link

**Comment by sararkd** [comment]
- About the note on 2.1. Yes, good I understand.
- Excercise 2.3 works now, excellent!
