### ISSUE TITLE
04.a-configure-CKAN.md - create admin in ckan

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-Training/B2FIND-Training#25]
Paster does not work as expected, if the user is unknown to CKAN, it aborts with this message.

```
(default) ubuntu@ckan:/usr/lib/ckan/default/src/ckan$ paster sysadmin add ckan_admin -c /etc/ckan/default/production.ini
User "ckan_admin" not found
Create new user: ckan_admin? [y/n]y
Need name and email of the user.
``` 

Workaround:
If user is already created inCKAN via the register button, the command above ca ne used to make the user an admin user.

**Comment by hwidmann** [comment]
In principle solved with commit 857d6a8def195a14b55a3c0c714a33d48cf18f27 ,
but teh figure could be located better in the md file.
