### ISSUE TITLE
01.b-generate-metadata.md - problem with example files

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-Training/B2FIND-Training#7]
- samples/DC_examples/fishProject/xml/Territorial-DC.xml for the fishproject, file is empty
- Territorial is a characteristic and should not have an own metadata record —> something is going wrong here, fix
- mdmanager script generates only 8 xml files in oaidata/fishproject-oai_dc/sample_1/xml/
./mdmanager.py --mode g -c fishproject -s samples/RAW_data/sample.csv --mdprefix oai_dc --mdsubset sample --verb comma
~/B2FIND-Training$ ls oaidata/fishproject-oai_dc/sample_1/xml/
Compressiceps.xml  Cylindricus.xml     Frontosa.xml     Multi.xml
ConvictJulie.xml   FiveBarCichlid.xml  GoldenJulie.xml  PrincessCichlid.xml
—> Is that correct?

**Comment by hwidmann** [comment]
- repopulated the directory samples/DC_examples/fishProject/xml/ (empty Territorial-DC.xml and other files removed)
- Yes, it is correct, that 8 xml files are generated, because sample.csv comprises 8 datasets (number of the lines minus one (because the first line lists the original field names))
